config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :accounts
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  def index
    @accounts = Account.where(user: current_user, status: "active")
  end

  def show
    @account
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(user: current_user, balance: 0, status: "active")

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @account.status = "inactive"
    @account.save!

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully inactivated." }
      format.json { head :no_content }
    end
  end

  private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:user_id, :balance, :status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  def index
    @transactions = Transaction.all
  end

  def show
  end

  def new
    @transaction = Transaction.new
  end

  def edit
  end

  def create
    @transaction = Transaction.new(transaction_params.merge(user: current_user))

    account = Account.find(@transaction.account_id)
    account.balance += transaction_params["value"].to_i
    account.save!

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(:account_id, :user_id, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p>
    <strong>User:</strong>
    <%= account.user_id %>
  </p>

  <p>
    <strong>Balance:</strong>
    <%= account.balance %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= account.status %>
  </p>

</div>

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :balance %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Accounts</h1>

<div id="accounts">
  <% @accounts.each do |account| %>
    <%= render account %>
    <p>
      <%= link_to "Show this account", account %>
    </p>
  <% end %>
</div>

<%= link_to "New account", new_account_path %>

app/views/accounts/new.html.erb
<div class="container">
  <h1>Criar nova conta!</h1>
  <%= render "form", account: @account %>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @account %>

<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>

  <%= button_to "Destroy this account", @account, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TesteDev</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<p style="color: green"><%= notice %></p>



<div class="container">
  <% if current_user%>
    <%= link_to "Criar nova conta", new_account_path %>
    <%= link_to "Minhas Contas", accounts_path %>
    <%= link_to "Transaćões", transactions_path %>
    <%= link_to "Enviar montante", new_transaction_path %>
  <% else %>
    Olá! Faća seu cadastro para visualizar
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Log out", destroy_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/transactions/_form.html.erb
<%= simple_form_for(@transaction) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    Para qual conta quer enviar?
    <%= f.association :account %>
    Qual valor?
    <%= f.input :value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Account:</strong>
    <%= transaction.account_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= transaction.user_id %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= transaction.value %>
  </p>

</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

<div id="transactions">
  <% @transactions.each do |transaction| %>
    <%= render transaction %>
    <p>
      <%= link_to "Show this transaction", transaction %>
    </p>
  <% end %>
</div>

<%= link_to "New transaction", new_transaction_path %>

app/views/transactions/new.html.erb
<div class="container">
<h1>Transaćão</h1>

<%= render "form", transaction: @transaction %>

<br>

  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>